[versions]
multiplatformTracy = "2.0.0"
kotlin = "2.1.0"
dokka = "1.9.20" # https://github.com/Kotlin/dokka/releases"
downloadTask = "5.6.0" # https://plugins.gradle.org/plugin/de.undercouch.download
tracy = "v0.11.1" # https://github.com/wolfpld/tracy/releases

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
downloadTask = { id = "de.undercouch.download", version.ref = "downloadTask" }
